### ISSUE TITLE
External Resource Usage

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/csaf-cms-backend#100]
The following stylesheets are loaded from external third-party hosts:
- https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
- https://unpkg.com/gutenberg-css
- https://unpkg.com/gutenberg-css/dist/themes/modern.min.css 
For instance, a potential issue regarding the usage of external resources might be a cross-domain leakage of the 
`Referrer` header.

_Originally posted by @pdamian_

**Comment by mfd2007** [comment]
the following two urls cannot be reproduced

- https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css

No other place can be found where these can be requested. Probably this belongs to secvisogram as frontend.

**Comment by tschmidtb51** [comment]
I guess they are either when generating the HMTL export or within the frontend...

**Comment by mfd2007** [comment]
fixed in #193
