### ISSUE TITLE
Workflow deadlock with invalid document

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/csaf-cms-backend#79]
If you create an CSAF document with an error (e.g. no Name of publisher) and the workflow state is changed to "RfPublication", there is no possibility to change the anymore. Only an error message "The document is not valid and can therefore not be published." is displayed.

There must be some kind of similar check before the workflow state change before.

**Comment by valentindey** [comment]
Should be fixed in d93cd74f7df3f5a22867bd47ae86eb25004ceeae (part of https://github.com/secvisogram/csaf-cms-backend/pull/82) which does document validation before changing workflow state to `RfPublication`
